create table public.django_migrations
(
    id      bigint generated by default as identity
        primary key,
    app     varchar(255)             not null,
    name    varchar(255)             not null,
    applied timestamp with time zone not null
);

alter table public.django_migrations
    owner to devuser;

create table public.django_content_type
(
    id        integer generated by default as identity
        primary key,
    app_label varchar(100) not null,
    model     varchar(100) not null,
    constraint django_content_type_app_label_model_76bd3d3b_uniq
        unique (app_label, model)
);

alter table public.django_content_type
    owner to devuser;

create table public.auth_permission
(
    id              integer generated by default as identity
        primary key,
    name            varchar(255) not null,
    content_type_id integer      not null
        constraint auth_permission_content_type_id_2f476e4b_fk_django_co
            references public.django_content_type
            deferrable initially deferred,
    codename        varchar(100) not null,
    constraint auth_permission_content_type_id_codename_01ab375a_uniq
        unique (content_type_id, codename)
);

alter table public.auth_permission
    owner to devuser;

create index auth_permission_content_type_id_2f476e4b
    on public.auth_permission (content_type_id);

create table public.auth_group
(
    id   integer generated by default as identity
        primary key,
    name varchar(150) not null
        unique
);

alter table public.auth_group
    owner to devuser;

create index auth_group_name_a6ea08ec_like
    on public.auth_group (name varchar_pattern_ops);

create table public.auth_group_permissions
(
    id            bigint generated by default as identity
        primary key,
    group_id      integer not null
        constraint auth_group_permissions_group_id_b120cbf9_fk_auth_group_id
            references public.auth_group
            deferrable initially deferred,
    permission_id integer not null
        constraint auth_group_permissio_permission_id_84c5c92e_fk_auth_perm
            references public.auth_permission
            deferrable initially deferred,
    constraint auth_group_permissions_group_id_permission_id_0cd325b0_uniq
        unique (group_id, permission_id)
);

alter table public.auth_group_permissions
    owner to devuser;

create index auth_group_permissions_group_id_b120cbf9
    on public.auth_group_permissions (group_id);

create index auth_group_permissions_permission_id_84c5c92e
    on public.auth_group_permissions (permission_id);

create table public.auth_user
(
    id           integer generated by default as identity
        primary key,
    password     varchar(128)             not null,
    last_login   timestamp with time zone,
    is_superuser boolean                  not null,
    username     varchar(150)             not null
        unique,
    first_name   varchar(150)             not null,
    last_name    varchar(150)             not null,
    email        varchar(254)             not null,
    is_staff     boolean                  not null,
    is_active    boolean                  not null,
    date_joined  timestamp with time zone not null
);

alter table public.auth_user
    owner to devuser;

create index auth_user_username_6821ab7c_like
    on public.auth_user (username varchar_pattern_ops);

create table public.auth_user_groups
(
    id       bigint generated by default as identity
        primary key,
    user_id  integer not null
        constraint auth_user_groups_user_id_6a12ed8b_fk_auth_user_id
            references public.auth_user
            deferrable initially deferred,
    group_id integer not null
        constraint auth_user_groups_group_id_97559544_fk_auth_group_id
            references public.auth_group
            deferrable initially deferred,
    constraint auth_user_groups_user_id_group_id_94350c0c_uniq
        unique (user_id, group_id)
);

alter table public.auth_user_groups
    owner to devuser;

create index auth_user_groups_user_id_6a12ed8b
    on public.auth_user_groups (user_id);

create index auth_user_groups_group_id_97559544
    on public.auth_user_groups (group_id);

create table public.auth_user_user_permissions
(
    id            bigint generated by default as identity
        primary key,
    user_id       integer not null
        constraint auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id
            references public.auth_user
            deferrable initially deferred,
    permission_id integer not null
        constraint auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm
            references public.auth_permission
            deferrable initially deferred,
    constraint auth_user_user_permissions_user_id_permission_id_14a6b632_uniq
        unique (user_id, permission_id)
);

alter table public.auth_user_user_permissions
    owner to devuser;

create index auth_user_user_permissions_user_id_a95ead1b
    on public.auth_user_user_permissions (user_id);

create index auth_user_user_permissions_permission_id_1fbb5f2c
    on public.auth_user_user_permissions (permission_id);

create table public.django_admin_log
(
    id              integer generated by default as identity
        primary key,
    action_time     timestamp with time zone not null,
    object_id       text,
    object_repr     varchar(200)             not null,
    action_flag     smallint                 not null
        constraint django_admin_log_action_flag_check
            check (action_flag >= 0),
    change_message  text                     not null,
    content_type_id integer
        constraint django_admin_log_content_type_id_c4bce8eb_fk_django_co
            references public.django_content_type
            deferrable initially deferred,
    user_id         integer                  not null
        constraint django_admin_log_user_id_c564eba6_fk_auth_user_id
            references public.auth_user
            deferrable initially deferred
);

alter table public.django_admin_log
    owner to devuser;

create index django_admin_log_content_type_id_c4bce8eb
    on public.django_admin_log (content_type_id);

create index django_admin_log_user_id_c564eba6
    on public.django_admin_log (user_id);

create table public.id_sequences
(
    sequence_key  varchar(50) not null
        primary key,
    current_value bigint      not null
);

alter table public.id_sequences
    owner to devuser;

create index id_sequences_sequence_key_e9ff2345_like
    on public.id_sequences (sequence_key varchar_pattern_ops);

create table public.tags
(
    id   varchar(20)  not null
        primary key,
    name varchar(100) not null
        unique,
    slug varchar(120) not null
        unique
);

alter table public.tags
    owner to devuser;

create index tags_id_7fdc8287_like
    on public.tags (id varchar_pattern_ops);

create index tags_name_d06e0d9e_like
    on public.tags (name varchar_pattern_ops);

create index tags_slug_92625acc_like
    on public.tags (slug varchar_pattern_ops);

create table public.legacy_users
(
    id           varchar(50)              not null
        primary key,
    last_login   timestamp with time zone,
    first_name   varchar(50)              not null,
    last_name    varchar(50)              not null,
    username     varchar(100)             not null
        unique,
    email        varchar(250)             not null
        unique,
    password     varchar(255)             not null,
    bio          varchar(200),
    avatar       varchar(200),
    phone_number varchar(50),
    phone_code   varchar(10),
    status       boolean                  not null,
    is_staff     boolean                  not null,
    is_superuser boolean                  not null,
    created_by   varchar(64),
    updated_by   varchar(64),
    deleted_by   varchar(64),
    created_at   timestamp with time zone not null,
    updated_at   timestamp with time zone not null,
    deleted_at   timestamp with time zone
);

alter table public.legacy_users
    owner to devuser;

create index legacy_users_id_e1e4e1b0_like
    on public.legacy_users (id varchar_pattern_ops);

create index legacy_users_username_babaae5a_like
    on public.legacy_users (username varchar_pattern_ops);

create index legacy_users_email_f8b90bc7_like
    on public.legacy_users (email varchar_pattern_ops);

create table public.users
(
    id                uuid                     not null
        primary key,
    email             varchar(255)             not null
        unique,
    phone_number      varchar(32)
        unique,
    password_hash     varchar(255),
    first_name        varchar(150),
    last_name         varchar(150),
    avatar_url        text,
    role              varchar(20)              not null,
    status            varchar(30)              not null,
    email_verified_at timestamp with time zone,
    phone_verified_at timestamp with time zone,
    created_at        timestamp with time zone not null,
    updated_at        timestamp with time zone not null,
    deleted_at        timestamp with time zone,
    created_by_id     uuid
        constraint users_created_by_id_19a92469_fk_users_id
            references public.users
            deferrable initially deferred,
    deleted_by_id     uuid
        constraint users_deleted_by_id_d342c553_fk_users_id
            references public.users
            deferrable initially deferred,
    updated_by_id     uuid
        constraint users_updated_by_id_283c532d_fk_users_id
            references public.users
            deferrable initially deferred
);

alter table public.users
    owner to devuser;

create index users_role_0ace22_idx
    on public.users (role);

create index users_status_9ca66f_idx
    on public.users (status);

create index users_deleted_e48316_idx
    on public.users (deleted_at);

create index users_email_0ea73cca_like
    on public.users (email varchar_pattern_ops);

create index users_phone_number_b4cde146_like
    on public.users (phone_number varchar_pattern_ops);

create index users_created_by_id_19a92469
    on public.users (created_by_id);

create index users_deleted_by_id_d342c553
    on public.users (deleted_by_id);

create index users_updated_by_id_283c532d
    on public.users (updated_by_id);

create table public.categories
(
    id            varchar(20)              not null
        primary key,
    name          varchar(255)             not null,
    slug          varchar(255)             not null
        unique,
    icon_url      text,
    image_url     text,
    sort_order    integer                  not null,
    status        varchar(10)              not null,
    created_at    timestamp with time zone not null,
    updated_at    timestamp with time zone not null,
    deleted_at    timestamp with time zone,
    parent_id     varchar(20)
        constraint categories_parent_id_fc02df82_fk_categories_id
            references public.categories
            deferrable initially deferred,
    created_by_id uuid
        constraint categories_created_by_id_05bc8fe3_fk_users_id
            references public.users
            deferrable initially deferred,
    deleted_by_id uuid
        constraint categories_deleted_by_id_a21415e4_fk_users_id
            references public.users
            deferrable initially deferred,
    updated_by_id uuid
        constraint categories_updated_by_id_2ec4118d_fk_users_id
            references public.users
            deferrable initially deferred
);

alter table public.categories
    owner to devuser;

create index categories_parent__7983b2_idx
    on public.categories (parent_id);

create index categories_status_dda6e6_idx
    on public.categories (status);

create index categories_id_aff88055_like
    on public.categories (id varchar_pattern_ops);

create index categories_slug_9bedfe6b_like
    on public.categories (slug varchar_pattern_ops);

create index categories_parent_id_fc02df82
    on public.categories (parent_id);

create index categories_parent_id_fc02df82_like
    on public.categories (parent_id varchar_pattern_ops);

create index categories_created_by_id_05bc8fe3
    on public.categories (created_by_id);

create index categories_deleted_by_id_a21415e4
    on public.categories (deleted_by_id);

create index categories_updated_by_id_2ec4118d
    on public.categories (updated_by_id);

create table public.carts
(
    id            varchar(20)              not null
        primary key,
    status        varchar(15)              not null,
    created_at    timestamp with time zone not null,
    updated_at    timestamp with time zone not null,
    deleted_at    timestamp with time zone,
    created_by_id uuid
        constraint carts_created_by_id_0e733e55_fk_users_id
            references public.users
            deferrable initially deferred,
    deleted_by_id uuid
        constraint carts_deleted_by_id_d5f89239_fk_users_id
            references public.users
            deferrable initially deferred,
    updated_by_id uuid
        constraint carts_updated_by_id_68d6fbfc_fk_users_id
            references public.users
            deferrable initially deferred,
    user_id       uuid                     not null
        constraint carts_user_id_3a9d1785_fk_users_id
            references public.users
            deferrable initially deferred
);

alter table public.carts
    owner to devuser;

create index carts_user_id_b1c689_idx
    on public.carts (user_id);

create index carts_id_7d97e392_like
    on public.carts (id varchar_pattern_ops);

create index carts_created_by_id_0e733e55
    on public.carts (created_by_id);

create index carts_deleted_by_id_d5f89239
    on public.carts (deleted_by_id);

create index carts_updated_by_id_68d6fbfc
    on public.carts (updated_by_id);

create index carts_user_id_3a9d1785
    on public.carts (user_id);

create table public.legal_documents
(
    id            varchar(12)              not null
        primary key,
    type          varchar(20)              not null,
    title         varchar(255)             not null,
    version       varchar(50)              not null,
    content       text                     not null,
    published_at  timestamp with time zone,
    status        varchar(10)              not null,
    created_at    timestamp with time zone not null,
    updated_at    timestamp with time zone not null,
    deleted_at    timestamp with time zone,
    created_by_id uuid
        constraint legal_documents_created_by_id_4d93a174_fk_users_id
            references public.users
            deferrable initially deferred,
    deleted_by_id uuid
        constraint legal_documents_deleted_by_id_523cbba4_fk_users_id
            references public.users
            deferrable initially deferred,
    updated_by_id uuid
        constraint legal_documents_updated_by_id_9cb4a1cf_fk_users_id
            references public.users
            deferrable initially deferred,
    constraint legal_documents_type_version_4c859b01_uniq
        unique (type, version)
);

alter table public.legal_documents
    owner to devuser;

create index legal_docum_type_0221a8_idx
    on public.legal_documents (type);

create index legal_docum_status_979ce4_idx
    on public.legal_documents (status);

create index legal_documents_id_43ea23f0_like
    on public.legal_documents (id varchar_pattern_ops);

create index legal_documents_created_by_id_4d93a174
    on public.legal_documents (created_by_id);

create index legal_documents_deleted_by_id_523cbba4
    on public.legal_documents (deleted_by_id);

create index legal_documents_updated_by_id_9cb4a1cf
    on public.legal_documents (updated_by_id);

create table public.legal_acceptances
(
    id                varchar(20)              not null
        primary key,
    accepted_at       timestamp with time zone not null,
    ip_address        inet,
    user_id           uuid                     not null
        constraint legal_acceptances_user_id_7c7f7053_fk_users_id
            references public.users
            deferrable initially deferred,
    legal_document_id varchar(12)              not null
        constraint legal_acceptances_legal_document_id_a0da4310_fk_legal_doc
            references public.legal_documents
            deferrable initially deferred,
    constraint legal_acceptances_user_id_legal_document_id_5f3a4884_uniq
        unique (user_id, legal_document_id)
);

alter table public.legal_acceptances
    owner to devuser;

create index legal_accep_user_id_ad53cb_idx
    on public.legal_acceptances (user_id);

create index legal_accep_legal_d_9bf998_idx
    on public.legal_acceptances (legal_document_id);

create index legal_acceptances_id_f04b5f94_like
    on public.legal_acceptances (id varchar_pattern_ops);

create index legal_acceptances_user_id_7c7f7053
    on public.legal_acceptances (user_id);

create index legal_acceptances_legal_document_id_a0da4310
    on public.legal_acceptances (legal_document_id);

create index legal_acceptances_legal_document_id_a0da4310_like
    on public.legal_acceptances (legal_document_id varchar_pattern_ops);

create table public.notifications
(
    id         varchar(20)              not null
        primary key,
    type       varchar(15)              not null,
    title      varchar(255)             not null,
    body       text,
    data       jsonb,
    read_at    timestamp with time zone,
    status     varchar(10)              not null,
    created_at timestamp with time zone not null,
    deleted_at timestamp with time zone,
    user_id    uuid                     not null
        constraint notifications_user_id_468e288d_fk_users_id
            references public.users
            deferrable initially deferred
);

alter table public.notifications
    owner to devuser;

create index notificatio_user_id_e78525_idx
    on public.notifications (user_id);

create index notificatio_type_8a8a78_idx
    on public.notifications (type);

create index notificatio_status_fce6f5_idx
    on public.notifications (status);

create index notificatio_read_at_392a1c_idx
    on public.notifications (read_at);

create index notifications_id_a89e44b1_like
    on public.notifications (id varchar_pattern_ops);

create index notifications_user_id_468e288d
    on public.notifications (user_id);

create table public.search_history
(
    id           bigint generated by default as identity
        primary key,
    query        varchar(500)             not null,
    filters_json jsonb,
    result_count integer,
    created_at   timestamp with time zone not null,
    user_id      uuid
        constraint search_history_user_id_b2c466f7_fk_users_id
            references public.users
            deferrable initially deferred,
    constraint unique_user_query
        unique (user_id, query)
);

alter table public.search_history
    owner to devuser;

create index search_hist_user_id_24152d_idx
    on public.search_history (user_id);

create index search_hist_query_69a772_idx
    on public.search_history (query);

create index search_history_user_id_b2c466f7
    on public.search_history (user_id);

create table public.stores
(
    id             varchar(20)              not null
        primary key,
    name           varchar(255)             not null,
    slug           varchar(255)             not null
        unique,
    description    text,
    logo_url       text,
    banner_url     text,
    status         varchar(15)              not null,
    rating_average numeric(3, 2)            not null,
    rating_count   integer                  not null,
    created_at     timestamp with time zone not null,
    updated_at     timestamp with time zone not null,
    deleted_at     timestamp with time zone,
    created_by_id  uuid
        constraint stores_created_by_id_298cf024_fk_users_id
            references public.users
            deferrable initially deferred,
    deleted_by_id  uuid
        constraint stores_deleted_by_id_4447df7f_fk_users_id
            references public.users
            deferrable initially deferred,
    owner_id       uuid                     not null
        constraint stores_owner_id_07b8e4d6_fk_users_id
            references public.users
            deferrable initially deferred,
    updated_by_id  uuid
        constraint stores_updated_by_id_79491367_fk_users_id
            references public.users
            deferrable initially deferred
);

alter table public.stores
    owner to devuser;

create table public.products
(
    id               varchar(20)              not null
        primary key,
    name             varchar(255)             not null,
    slug             varchar(255)             not null,
    description      text,
    base_price       numeric(12, 2)           not null,
    compare_at_price numeric(12, 2),
    currency         varchar(3)               not null,
    sku              varchar(100),
    status           varchar(15)              not null,
    rating_average   numeric(3, 2)            not null,
    rating_count     integer                  not null,
    sold_count       integer                  not null,
    created_at       timestamp with time zone not null,
    updated_at       timestamp with time zone not null,
    deleted_at       timestamp with time zone,
    category_id      varchar(20)
        constraint products_category_id_a7a3a156_fk_categories_id
            references public.categories
            deferrable initially deferred,
    created_by_id    uuid
        constraint products_created_by_id_924ff91a_fk_users_id
            references public.users
            deferrable initially deferred,
    deleted_by_id    uuid
        constraint products_deleted_by_id_e4330cc2_fk_users_id
            references public.users
            deferrable initially deferred,
    updated_by_id    uuid
        constraint products_updated_by_id_65dc5679_fk_users_id
            references public.users
            deferrable initially deferred,
    store_id         varchar(20)              not null
        constraint products_store_id_5412147b_fk_stores_id
            references public.stores
            deferrable initially deferred,
    constraint products_store_id_slug_28d59249_uniq
        unique (store_id, slug)
);

alter table public.products
    owner to devuser;

create index products_store_i_4a84a2_idx
    on public.products (store_id);

create index products_categor_4083ff_idx
    on public.products (category_id);

create index products_name_6f9890_idx
    on public.products (name);

create index products_status_a30e64_idx
    on public.products (status);

create index products_deleted_c3f9ae_idx
    on public.products (deleted_at);

create index products_id_bc050757_like
    on public.products (id varchar_pattern_ops);

create index products_category_id_a7a3a156
    on public.products (category_id);

create index products_category_id_a7a3a156_like
    on public.products (category_id varchar_pattern_ops);

create index products_created_by_id_924ff91a
    on public.products (created_by_id);

create index products_deleted_by_id_e4330cc2
    on public.products (deleted_by_id);

create index products_updated_by_id_65dc5679
    on public.products (updated_by_id);

create index products_store_id_5412147b
    on public.products (store_id);

create index products_store_id_5412147b_like
    on public.products (store_id varchar_pattern_ops);

create table public.favorites
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp with time zone not null,
    deleted_at timestamp with time zone,
    user_id    uuid                     not null
        constraint favorites_user_id_d60eb79f_fk_users_id
            references public.users
            deferrable initially deferred,
    product_id varchar(20)              not null
        constraint favorites_product_id_20deaadd_fk_products_id
            references public.products
            deferrable initially deferred
);

alter table public.favorites
    owner to devuser;

create index favorites_user_id_bc3324_idx
    on public.favorites (user_id);

create index favorites_product_7d70f0_idx
    on public.favorites (product_id);

create index favorites_user_id_d60eb79f
    on public.favorites (user_id);

create index favorites_product_id_20deaadd
    on public.favorites (product_id);

create index favorites_product_id_20deaadd_like
    on public.favorites (product_id varchar_pattern_ops);

create table public.product_images
(
    id            varchar(20)              not null
        primary key,
    image_url     text                     not null,
    alt_text      varchar(255),
    sort_order    integer                  not null,
    is_primary    boolean                  not null,
    created_at    timestamp with time zone not null,
    updated_at    timestamp with time zone not null,
    deleted_at    timestamp with time zone,
    created_by_id uuid
        constraint product_images_created_by_id_11bb236b_fk_users_id
            references public.users
            deferrable initially deferred,
    deleted_by_id uuid
        constraint product_images_deleted_by_id_9fca51bd_fk_users_id
            references public.users
            deferrable initially deferred,
    product_id    varchar(20)              not null
        constraint product_images_product_id_28ebf5f0_fk_products_id
            references public.products
            deferrable initially deferred,
    updated_by_id uuid
        constraint product_images_updated_by_id_b5803f3f_fk_users_id
            references public.users
            deferrable initially deferred
);

alter table public.product_images
    owner to devuser;

create index product_ima_product_55415d_idx
    on public.product_images (product_id);

create index product_images_id_101b8629_like
    on public.product_images (id varchar_pattern_ops);

create index product_images_created_by_id_11bb236b
    on public.product_images (created_by_id);

create index product_images_deleted_by_id_9fca51bd
    on public.product_images (deleted_by_id);

create index product_images_product_id_28ebf5f0
    on public.product_images (product_id);

create index product_images_product_id_28ebf5f0_like
    on public.product_images (product_id varchar_pattern_ops);

create index product_images_updated_by_id_b5803f3f
    on public.product_images (updated_by_id);

create table public.product_variants
(
    id             varchar(20)              not null
        primary key,
    sku            varchar(100)
        unique,
    name           varchar(255)             not null,
    price          numeric(12, 2),
    stock_quantity integer                  not null,
    status         varchar(15)              not null,
    created_at     timestamp with time zone not null,
    updated_at     timestamp with time zone not null,
    deleted_at     timestamp with time zone,
    created_by_id  uuid
        constraint product_variants_created_by_id_534f38a5_fk_users_id
            references public.users
            deferrable initially deferred,
    deleted_by_id  uuid
        constraint product_variants_deleted_by_id_61534226_fk_users_id
            references public.users
            deferrable initially deferred,
    product_id     varchar(20)              not null
        constraint product_variants_product_id_019d9f04_fk_products_id
            references public.products
            deferrable initially deferred,
    updated_by_id  uuid
        constraint product_variants_updated_by_id_74207772_fk_users_id
            references public.users
            deferrable initially deferred
);

alter table public.product_variants
    owner to devuser;

create index product_var_product_017fde_idx
    on public.product_variants (product_id);

create index product_var_status_9f7d54_idx
    on public.product_variants (status);

create index product_variants_id_f6752e09_like
    on public.product_variants (id varchar_pattern_ops);

create index product_variants_sku_10738fd7_like
    on public.product_variants (sku varchar_pattern_ops);

create index product_variants_created_by_id_534f38a5
    on public.product_variants (created_by_id);

create index product_variants_deleted_by_id_61534226
    on public.product_variants (deleted_by_id);

create index product_variants_product_id_019d9f04
    on public.product_variants (product_id);

create index product_variants_product_id_019d9f04_like
    on public.product_variants (product_id varchar_pattern_ops);

create index product_variants_updated_by_id_74207772
    on public.product_variants (updated_by_id);

create table public.cart_items
(
    id                  varchar(20)              not null
        primary key,
    quantity            integer                  not null,
    unit_price_snapshot numeric(12, 2)           not null,
    is_selected         boolean                  not null,
    created_at          timestamp with time zone not null,
    updated_at          timestamp with time zone not null,
    deleted_at          timestamp with time zone,
    cart_id             varchar(20)              not null
        constraint cart_items_cart_id_54d2714b_fk_carts_id
            references public.carts
            deferrable initially deferred,
    created_by_id       uuid
        constraint cart_items_created_by_id_bdffc51d_fk_users_id
            references public.users
            deferrable initially deferred,
    deleted_by_id       uuid
        constraint cart_items_deleted_by_id_1b8b26f7_fk_users_id
            references public.users
            deferrable initially deferred,
    updated_by_id       uuid
        constraint cart_items_updated_by_id_5c456b4e_fk_users_id
            references public.users
            deferrable initially deferred,
    product_id          varchar(20)              not null
        constraint cart_items_product_id_9398bb89_fk_products_id
            references public.products
            deferrable initially deferred,
    product_variant_id  varchar(20)
        constraint cart_items_product_variant_id_5e435223_fk_product_variants_id
            references public.product_variants
            deferrable initially deferred
);

alter table public.cart_items
    owner to devuser;

create index cart_items_cart_id_3caa7d_idx
    on public.cart_items (cart_id);

create index cart_items_product_6a1de7_idx
    on public.cart_items (product_id);

create index cart_items_id_9bbcdd2a_like
    on public.cart_items (id varchar_pattern_ops);

create index cart_items_cart_id_54d2714b
    on public.cart_items (cart_id);

create index cart_items_cart_id_54d2714b_like
    on public.cart_items (cart_id varchar_pattern_ops);

create index cart_items_created_by_id_bdffc51d
    on public.cart_items (created_by_id);

create index cart_items_deleted_by_id_1b8b26f7
    on public.cart_items (deleted_by_id);

create index cart_items_updated_by_id_5c456b4e
    on public.cart_items (updated_by_id);

create index cart_items_product_id_9398bb89
    on public.cart_items (product_id);

create index cart_items_product_id_9398bb89_like
    on public.cart_items (product_id varchar_pattern_ops);

create index cart_items_product_variant_id_5e435223
    on public.cart_items (product_variant_id);

create index cart_items_product_variant_id_5e435223_like
    on public.cart_items (product_variant_id varchar_pattern_ops);

create index stores_owner_i_c77c42_idx
    on public.stores (owner_id);

create index stores_status_ecb921_idx
    on public.stores (status);

create index stores_id_af731864_like
    on public.stores (id varchar_pattern_ops);

create index stores_slug_c8d524d0_like
    on public.stores (slug varchar_pattern_ops);

create index stores_created_by_id_298cf024
    on public.stores (created_by_id);

create index stores_deleted_by_id_4447df7f
    on public.stores (deleted_by_id);

create index stores_owner_id_07b8e4d6
    on public.stores (owner_id);

create index stores_updated_by_id_79491367
    on public.stores (updated_by_id);

create table public.product_tags
(
    id         varchar(20) not null
        primary key,
    product_id varchar(20) not null
        constraint product_tags_product_id_138ace6f_fk_products_id
            references public.products
            deferrable initially deferred,
    tag_id     varchar(20) not null
        constraint product_tags_tag_id_dd3a8625_fk_tags_id
            references public.tags
            deferrable initially deferred,
    constraint product_tags_product_id_tag_id_98fbee9e_uniq
        unique (product_id, tag_id)
);

alter table public.product_tags
    owner to devuser;

create index product_tag_product_2909de_idx
    on public.product_tags (product_id);

create index product_tag_tag_id_b717e2_idx
    on public.product_tags (tag_id);

create index product_tags_id_f4d6828f_like
    on public.product_tags (id varchar_pattern_ops);

create index product_tags_product_id_138ace6f
    on public.product_tags (product_id);

create index product_tags_product_id_138ace6f_like
    on public.product_tags (product_id varchar_pattern_ops);

create index product_tags_tag_id_dd3a8625
    on public.product_tags (tag_id);

create index product_tags_tag_id_dd3a8625_like
    on public.product_tags (tag_id varchar_pattern_ops);

create table public.user_addresses
(
    id             varchar(20)              not null
        primary key,
    label          varchar(100),
    recipient_name varchar(255)             not null,
    phone_number   varchar(32)              not null,
    address_line_1 varchar(255)             not null,
    address_line_2 varchar(255),
    city           varchar(120)             not null,
    state          varchar(120),
    postal_code    varchar(32),
    country_code   varchar(2)               not null,
    latitude       numeric(10, 7),
    longitude      numeric(10, 7),
    is_default     boolean                  not null,
    created_at     timestamp with time zone not null,
    updated_at     timestamp with time zone not null,
    deleted_at     timestamp with time zone,
    created_by_id  uuid
        constraint user_addresses_created_by_id_3b7dea9a_fk_users_id
            references public.users
            deferrable initially deferred,
    deleted_by_id  uuid
        constraint user_addresses_deleted_by_id_47754b08_fk_users_id
            references public.users
            deferrable initially deferred,
    updated_by_id  uuid
        constraint user_addresses_updated_by_id_c1cc2b6d_fk_users_id
            references public.users
            deferrable initially deferred,
    user_id        uuid                     not null
        constraint user_addresses_user_id_c7113441_fk_users_id
            references public.users
            deferrable initially deferred
);

alter table public.user_addresses
    owner to devuser;

create table public.orders
(
    id                  varchar(30)              not null
        primary key,
    status              varchar(15)              not null,
    subtotal_amount     numeric(12, 2)           not null,
    shipping_amount     numeric(12, 2)           not null,
    discount_amount     numeric(12, 2)           not null,
    tax_amount          numeric(12, 2)           not null,
    total_amount        numeric(12, 2)           not null,
    currency            varchar(3)               not null,
    placed_at           timestamp with time zone,
    cancelled_at        timestamp with time zone,
    created_at          timestamp with time zone not null,
    updated_at          timestamp with time zone not null,
    deleted_at          timestamp with time zone,
    created_by_id       uuid
        constraint orders_created_by_id_b9de303d_fk_users_id
            references public.users
            deferrable initially deferred,
    deleted_by_id       uuid
        constraint orders_deleted_by_id_48ac0725_fk_users_id
            references public.users
            deferrable initially deferred,
    updated_by_id       uuid
        constraint orders_updated_by_id_04a74b30_fk_users_id
            references public.users
            deferrable initially deferred,
    user_id             uuid                     not null
        constraint orders_user_id_7e2523fb_fk_users_id
            references public.users
            deferrable initially deferred,
    store_id            varchar(20)              not null
        constraint orders_store_id_04cf6eb1_fk_stores_id
            references public.stores
            deferrable initially deferred,
    shipping_address_id varchar(20)
        constraint orders_shipping_address_id_bf7237b0_fk_user_addresses_id
            references public.user_addresses
            deferrable initially deferred
);

alter table public.orders
    owner to devuser;

create table public.conversations
(
    id              varchar(20)              not null
        primary key,
    status          varchar(10)              not null,
    last_message_at timestamp with time zone,
    created_at      timestamp with time zone not null,
    updated_at      timestamp with time zone not null,
    deleted_at      timestamp with time zone,
    created_by_id   uuid
        constraint conversations_created_by_id_67a75e1e_fk_users_id
            references public.users
            deferrable initially deferred,
    customer_id     uuid                     not null
        constraint conversations_customer_id_de8ac2f3_fk_users_id
            references public.users
            deferrable initially deferred,
    deleted_by_id   uuid
        constraint conversations_deleted_by_id_3e455177_fk_users_id
            references public.users
            deferrable initially deferred,
    updated_by_id   uuid
        constraint conversations_updated_by_id_8dfdf2d5_fk_users_id
            references public.users
            deferrable initially deferred,
    order_id        varchar(30)
        constraint conversations_order_id_cfac4089_fk_orders_id
            references public.orders
            deferrable initially deferred,
    store_id        varchar(20)
        constraint conversations_store_id_492e830b_fk_stores_id
            references public.stores
            deferrable initially deferred
);

alter table public.conversations
    owner to devuser;

create index conversatio_custome_90c827_idx
    on public.conversations (customer_id);

create index conversatio_store_i_a76fda_idx
    on public.conversations (store_id);

create index conversatio_order_i_027355_idx
    on public.conversations (order_id);

create index conversatio_status_742c74_idx
    on public.conversations (status);

create index conversations_id_65f7c9ea_like
    on public.conversations (id varchar_pattern_ops);

create index conversations_created_by_id_67a75e1e
    on public.conversations (created_by_id);

create index conversations_customer_id_de8ac2f3
    on public.conversations (customer_id);

create index conversations_deleted_by_id_3e455177
    on public.conversations (deleted_by_id);

create index conversations_updated_by_id_8dfdf2d5
    on public.conversations (updated_by_id);

create index conversations_order_id_cfac4089
    on public.conversations (order_id);

create index conversations_order_id_cfac4089_like
    on public.conversations (order_id varchar_pattern_ops);

create index conversations_store_id_492e830b
    on public.conversations (store_id);

create index conversations_store_id_492e830b_like
    on public.conversations (store_id varchar_pattern_ops);

create table public.messages
(
    id              varchar(20)              not null
        primary key,
    message_type    varchar(10)              not null,
    body            text,
    attachment_url  text,
    read_at         timestamp with time zone,
    created_at      timestamp with time zone not null,
    deleted_at      timestamp with time zone,
    conversation_id varchar(20)              not null
        constraint messages_conversation_id_5ef638db_fk_conversations_id
            references public.conversations
            deferrable initially deferred,
    sender_id       uuid                     not null
        constraint messages_sender_id_dc5a0bbd_fk_users_id
            references public.users
            deferrable initially deferred
);

alter table public.messages
    owner to devuser;

create index messages_convers_8904b4_idx
    on public.messages (conversation_id);

create index messages_sender__6ae55a_idx
    on public.messages (sender_id);

create index messages_created_919c58_idx
    on public.messages (created_at);

create index messages_id_8dabb0e5_like
    on public.messages (id varchar_pattern_ops);

create index messages_conversation_id_5ef638db
    on public.messages (conversation_id);

create index messages_conversation_id_5ef638db_like
    on public.messages (conversation_id varchar_pattern_ops);

create index messages_sender_id_dc5a0bbd
    on public.messages (sender_id);

create index orders_user_id_4e08b8_idx
    on public.orders (user_id);

create index orders_store_i_9c629c_idx
    on public.orders (store_id);

create index orders_status_762191_idx
    on public.orders (status);

create index orders_placed__34697f_idx
    on public.orders (placed_at);

create index orders_id_ecea5967_like
    on public.orders (id varchar_pattern_ops);

create index orders_created_by_id_b9de303d
    on public.orders (created_by_id);

create index orders_deleted_by_id_48ac0725
    on public.orders (deleted_by_id);

create index orders_updated_by_id_04a74b30
    on public.orders (updated_by_id);

create index orders_user_id_7e2523fb
    on public.orders (user_id);

create index orders_store_id_04cf6eb1
    on public.orders (store_id);

create index orders_store_id_04cf6eb1_like
    on public.orders (store_id varchar_pattern_ops);

create index orders_shipping_address_id_bf7237b0
    on public.orders (shipping_address_id);

create index orders_shipping_address_id_bf7237b0_like
    on public.orders (shipping_address_id varchar_pattern_ops);

create table public.order_status_history
(
    id            varchar(20)              not null
        primary key,
    from_status   varchar(15),
    to_status     varchar(15)              not null,
    note          text,
    created_at    timestamp with time zone not null,
    changed_by_id uuid
        constraint order_status_history_changed_by_id_f13feb0a_fk_users_id
            references public.users
            deferrable initially deferred,
    order_id      varchar(30)              not null
        constraint order_status_history_order_id_d33fdfde_fk_orders_id
            references public.orders
            deferrable initially deferred
);

alter table public.order_status_history
    owner to devuser;

create index order_statu_order_i_8ab903_idx
    on public.order_status_history (order_id);

create index order_status_history_id_d94e59a1_like
    on public.order_status_history (id varchar_pattern_ops);

create index order_status_history_changed_by_id_f13feb0a
    on public.order_status_history (changed_by_id);

create index order_status_history_order_id_d33fdfde
    on public.order_status_history (order_id);

create index order_status_history_order_id_d33fdfde_like
    on public.order_status_history (order_id varchar_pattern_ops);

create table public.order_items
(
    id                    varchar(20)              not null
        primary key,
    product_name_snapshot varchar(255)             not null,
    variant_name_snapshot varchar(255),
    sku_snapshot          varchar(100),
    unit_price            numeric(12, 2)           not null,
    quantity              integer                  not null,
    line_total            numeric(12, 2)           not null,
    created_at            timestamp with time zone not null,
    updated_at            timestamp with time zone not null,
    deleted_at            timestamp with time zone,
    created_by_id         uuid
        constraint order_items_created_by_id_167363ee_fk_users_id
            references public.users
            deferrable initially deferred,
    deleted_by_id         uuid
        constraint order_items_deleted_by_id_b1fcc7e4_fk_users_id
            references public.users
            deferrable initially deferred,
    order_id              varchar(30)              not null
        constraint order_items_order_id_412ad78b_fk_orders_id
            references public.orders
            deferrable initially deferred,
    updated_by_id         uuid
        constraint order_items_updated_by_id_503d6835_fk_users_id
            references public.users
            deferrable initially deferred,
    product_id            varchar(20)
        constraint order_items_product_id_dd557d5a_fk_products_id
            references public.products
            deferrable initially deferred,
    product_variant_id    varchar(20)
        constraint order_items_product_variant_id_a2528b5c_fk_product_variants_id
            references public.product_variants
            deferrable initially deferred
);

alter table public.order_items
    owner to devuser;

create index order_items_order_i_26ad88_idx
    on public.order_items (order_id);

create index order_items_product_a53db1_idx
    on public.order_items (product_id);

create index order_items_id_252e703e_like
    on public.order_items (id varchar_pattern_ops);

create index order_items_created_by_id_167363ee
    on public.order_items (created_by_id);

create index order_items_deleted_by_id_b1fcc7e4
    on public.order_items (deleted_by_id);

create index order_items_order_id_412ad78b
    on public.order_items (order_id);

create index order_items_order_id_412ad78b_like
    on public.order_items (order_id varchar_pattern_ops);

create index order_items_updated_by_id_503d6835
    on public.order_items (updated_by_id);

create index order_items_product_id_dd557d5a
    on public.order_items (product_id);

create index order_items_product_id_dd557d5a_like
    on public.order_items (product_id varchar_pattern_ops);

create index order_items_product_variant_id_a2528b5c
    on public.order_items (product_variant_id);

create index order_items_product_variant_id_a2528b5c_like
    on public.order_items (product_variant_id varchar_pattern_ops);

create table public.reviews
(
    id                   varchar(20)              not null
        primary key,
    rating               integer                  not null,
    title                varchar(255),
    body                 text,
    is_verified_purchase boolean                  not null,
    created_at           timestamp with time zone not null,
    updated_at           timestamp with time zone not null,
    deleted_at           timestamp with time zone,
    order_item_id        varchar(20)
        constraint reviews_order_item_id_78ca69ec_fk_order_items_id
            references public.order_items
            deferrable initially deferred,
    product_id           varchar(20)              not null
        constraint reviews_product_id_d4b78cfe_fk_products_id
            references public.products
            deferrable initially deferred,
    product_variant_id   varchar(20)
        constraint reviews_product_variant_id_116dc43f_fk_product_variants_id
            references public.product_variants
            deferrable initially deferred,
    user_id              uuid                     not null
        constraint reviews_user_id_c23b0903_fk_users_id
            references public.users
            deferrable initially deferred
);

alter table public.reviews
    owner to devuser;

create index reviews_user_id_79db63_idx
    on public.reviews (user_id);

create index reviews_product_3516b2_idx
    on public.reviews (product_id);

create index reviews_rating_17e8a4_idx
    on public.reviews (rating);

create index reviews_id_4bca8ef3_like
    on public.reviews (id varchar_pattern_ops);

create index reviews_order_item_id_78ca69ec
    on public.reviews (order_item_id);

create index reviews_order_item_id_78ca69ec_like
    on public.reviews (order_item_id varchar_pattern_ops);

create index reviews_product_id_d4b78cfe
    on public.reviews (product_id);

create index reviews_product_id_d4b78cfe_like
    on public.reviews (product_id varchar_pattern_ops);

create index reviews_product_variant_id_116dc43f
    on public.reviews (product_variant_id);

create index reviews_product_variant_id_116dc43f_like
    on public.reviews (product_variant_id varchar_pattern_ops);

create index reviews_user_id_c23b0903
    on public.reviews (user_id);

create table public.shipments
(
    id              varchar(20)              not null
        primary key,
    carrier_name    varchar(100),
    tracking_number varchar(100),
    status          varchar(20)              not null,
    shipped_at      timestamp with time zone,
    delivered_at    timestamp with time zone,
    created_at      timestamp with time zone not null,
    updated_at      timestamp with time zone not null,
    deleted_at      timestamp with time zone,
    created_by_id   uuid
        constraint shipments_created_by_id_a64f6e7f_fk_users_id
            references public.users
            deferrable initially deferred,
    deleted_by_id   uuid
        constraint shipments_deleted_by_id_54270002_fk_users_id
            references public.users
            deferrable initially deferred,
    order_id        varchar(30)              not null
        constraint shipments_order_id_cd5ec97c_fk_orders_id
            references public.orders
            deferrable initially deferred,
    updated_by_id   uuid
        constraint shipments_updated_by_id_f3b3dac9_fk_users_id
            references public.users
            deferrable initially deferred
);

alter table public.shipments
    owner to devuser;

create index shipments_order_i_f8cde1_idx
    on public.shipments (order_id);

create index shipments_status_cda325_idx
    on public.shipments (status);

create index shipments_trackin_cc256d_idx
    on public.shipments (tracking_number);

create index shipments_id_6b89e8de_like
    on public.shipments (id varchar_pattern_ops);

create index shipments_created_by_id_a64f6e7f
    on public.shipments (created_by_id);

create index shipments_deleted_by_id_54270002
    on public.shipments (deleted_by_id);

create index shipments_order_id_cd5ec97c
    on public.shipments (order_id);

create index shipments_order_id_cd5ec97c_like
    on public.shipments (order_id varchar_pattern_ops);

create index shipments_updated_by_id_f3b3dac9
    on public.shipments (updated_by_id);

create table public.shipment_events
(
    id          varchar(20)              not null
        primary key,
    status      varchar(20)              not null,
    location    varchar(255),
    description text,
    event_time  timestamp with time zone not null,
    created_at  timestamp with time zone not null,
    shipment_id varchar(20)              not null
        constraint shipment_events_shipment_id_792ff45a_fk_shipments_id
            references public.shipments
            deferrable initially deferred
);

alter table public.shipment_events
    owner to devuser;

create index shipment_ev_shipmen_83ad8b_idx
    on public.shipment_events (shipment_id);

create index shipment_ev_event_t_abe4bf_idx
    on public.shipment_events (event_time);

create index shipment_events_id_4182ec8a_like
    on public.shipment_events (id varchar_pattern_ops);

create index shipment_events_shipment_id_792ff45a
    on public.shipment_events (shipment_id);

create index shipment_events_shipment_id_792ff45a_like
    on public.shipment_events (shipment_id varchar_pattern_ops);

create table public.support_tickets
(
    id            varchar(20)              not null
        primary key,
    subject       varchar(255)             not null,
    category      varchar(15)              not null,
    status        varchar(10)              not null,
    priority      varchar(10)              not null,
    created_at    timestamp with time zone not null,
    updated_at    timestamp with time zone not null,
    deleted_at    timestamp with time zone,
    created_by_id uuid
        constraint support_tickets_created_by_id_8d3c2401_fk_users_id
            references public.users
            deferrable initially deferred,
    deleted_by_id uuid
        constraint support_tickets_deleted_by_id_8d44fe7f_fk_users_id
            references public.users
            deferrable initially deferred,
    order_id      varchar(30)
        constraint support_tickets_order_id_52e2f024_fk_orders_id
            references public.orders
            deferrable initially deferred,
    updated_by_id uuid
        constraint support_tickets_updated_by_id_3f3ee764_fk_users_id
            references public.users
            deferrable initially deferred,
    user_id       uuid                     not null
        constraint support_tickets_user_id_2e4c3168_fk_users_id
            references public.users
            deferrable initially deferred
);

alter table public.support_tickets
    owner to devuser;

create index support_tic_user_id_f7e679_idx
    on public.support_tickets (user_id);

create index support_tic_order_i_c52654_idx
    on public.support_tickets (order_id);

create index support_tic_status_ac1ffd_idx
    on public.support_tickets (status);

create index support_tickets_id_e2eb6928_like
    on public.support_tickets (id varchar_pattern_ops);

create index support_tickets_created_by_id_8d3c2401
    on public.support_tickets (created_by_id);

create index support_tickets_deleted_by_id_8d44fe7f
    on public.support_tickets (deleted_by_id);

create index support_tickets_order_id_52e2f024
    on public.support_tickets (order_id);

create index support_tickets_order_id_52e2f024_like
    on public.support_tickets (order_id varchar_pattern_ops);

create index support_tickets_updated_by_id_3f3ee764
    on public.support_tickets (updated_by_id);

create index support_tickets_user_id_2e4c3168
    on public.support_tickets (user_id);

create table public.support_ticket_messages
(
    id             varchar(20)              not null
        primary key,
    body           text                     not null,
    attachment_url text,
    created_at     timestamp with time zone not null,
    deleted_at     timestamp with time zone,
    sender_id      uuid                     not null
        constraint support_ticket_messages_sender_id_eeb9cba3_fk_users_id
            references public.users
            deferrable initially deferred,
    ticket_id      varchar(20)              not null
        constraint support_ticket_messa_ticket_id_e46e48c2_fk_support_t
            references public.support_tickets
            deferrable initially deferred
);

alter table public.support_ticket_messages
    owner to devuser;

create index support_tic_ticket__acb76b_idx
    on public.support_ticket_messages (ticket_id);

create index support_tic_sender__e5d81a_idx
    on public.support_ticket_messages (sender_id);

create index support_ticket_messages_id_7b50e054_like
    on public.support_ticket_messages (id varchar_pattern_ops);

create index support_ticket_messages_sender_id_eeb9cba3
    on public.support_ticket_messages (sender_id);

create index support_ticket_messages_ticket_id_e46e48c2
    on public.support_ticket_messages (ticket_id);

create index support_ticket_messages_ticket_id_e46e48c2_like
    on public.support_ticket_messages (ticket_id varchar_pattern_ops);

create index user_addres_user_id_0ee5d5_idx
    on public.user_addresses (user_id);

create index user_addresses_id_c08d058c_like
    on public.user_addresses (id varchar_pattern_ops);

create index user_addresses_created_by_id_3b7dea9a
    on public.user_addresses (created_by_id);

create index user_addresses_deleted_by_id_47754b08
    on public.user_addresses (deleted_by_id);

create index user_addresses_updated_by_id_c1cc2b6d
    on public.user_addresses (updated_by_id);

create index user_addresses_user_id_c7113441
    on public.user_addresses (user_id);

create table public.user_profiles
(
    id                 uuid                     not null
        primary key,
    date_of_birth      date,
    gender             varchar(20),
    preferred_language varchar(10)              not null,
    marketing_opt_in   boolean                  not null,
    created_at         timestamp with time zone not null,
    updated_at         timestamp with time zone not null,
    deleted_at         timestamp with time zone,
    created_by_id      uuid
        constraint user_profiles_created_by_id_e23d6f71_fk_users_id
            references public.users
            deferrable initially deferred,
    deleted_by_id      uuid
        constraint user_profiles_deleted_by_id_ab512b05_fk_users_id
            references public.users
            deferrable initially deferred,
    updated_by_id      uuid
        constraint user_profiles_updated_by_id_f4529171_fk_users_id
            references public.users
            deferrable initially deferred,
    user_id            uuid                     not null
        unique
        constraint user_profiles_user_id_8c5ab5fe_fk_users_id
            references public.users
            deferrable initially deferred
);

alter table public.user_profiles
    owner to devuser;

create index user_profiles_created_by_id_e23d6f71
    on public.user_profiles (created_by_id);

create index user_profiles_deleted_by_id_ab512b05
    on public.user_profiles (deleted_by_id);

create index user_profiles_updated_by_id_f4529171
    on public.user_profiles (updated_by_id);

create table public.user_security_settings
(
    id                       uuid                     not null
        primary key,
    two_factor_enabled       boolean                  not null,
    biometric_enabled        boolean                  not null,
    last_password_changed_at timestamp with time zone,
    created_at               timestamp with time zone not null,
    updated_at               timestamp with time zone not null,
    deleted_at               timestamp with time zone,
    created_by_id            uuid
        constraint user_security_settings_created_by_id_79c37b2e_fk_users_id
            references public.users
            deferrable initially deferred,
    deleted_by_id            uuid
        constraint user_security_settings_deleted_by_id_1fbc9de5_fk_users_id
            references public.users
            deferrable initially deferred,
    updated_by_id            uuid
        constraint user_security_settings_updated_by_id_89d5f71e_fk_users_id
            references public.users
            deferrable initially deferred,
    user_id                  uuid                     not null
        unique
        constraint user_security_settings_user_id_e931bebb_fk_users_id
            references public.users
            deferrable initially deferred
);

alter table public.user_security_settings
    owner to devuser;

create index user_security_settings_created_by_id_79c37b2e
    on public.user_security_settings (created_by_id);

create index user_security_settings_deleted_by_id_1fbc9de5
    on public.user_security_settings (deleted_by_id);

create index user_security_settings_updated_by_id_89d5f71e
    on public.user_security_settings (updated_by_id);

create table public.user_sessions
(
    id           uuid                     not null
        primary key,
    device_name  varchar(255),
    ip_address   inet,
    user_agent   text,
    last_seen_at timestamp with time zone,
    revoked_at   timestamp with time zone,
    created_at   timestamp with time zone not null,
    user_id      uuid                     not null
        constraint user_sessions_user_id_43ce9642_fk_users_id
            references public.users
            deferrable initially deferred
);

alter table public.user_sessions
    owner to devuser;

create index user_sessio_user_id_eb20aa_idx
    on public.user_sessions (user_id);

create index user_sessio_revoked_759f1e_idx
    on public.user_sessions (revoked_at);

create index user_sessions_user_id_43ce9642
    on public.user_sessions (user_id);

create table public.variant_options
(
    id                 varchar(20)  not null
        primary key,
    name               varchar(100) not null,
    value              varchar(100) not null,
    product_variant_id varchar(20)  not null
        constraint variant_options_product_variant_id_3962d4d8_fk_product_v
            references public.product_variants
            deferrable initially deferred,
    constraint variant_options_product_variant_id_name_7aab9e84_uniq
        unique (product_variant_id, name)
);

alter table public.variant_options
    owner to devuser;

create index variant_options_id_ba5a07f0_like
    on public.variant_options (id varchar_pattern_ops);

create index variant_options_product_variant_id_3962d4d8
    on public.variant_options (product_variant_id);

create index variant_options_product_variant_id_3962d4d8_like
    on public.variant_options (product_variant_id varchar_pattern_ops);

create table public.django_session
(
    session_key  varchar(40)              not null
        primary key,
    session_data text                     not null,
    expire_date  timestamp with time zone not null
);

alter table public.django_session
    owner to devuser;

create index django_session_session_key_c0390e0f_like
    on public.django_session (session_key varchar_pattern_ops);

create index django_session_expire_date_a5c62663
    on public.django_session (expire_date);