# Generated by Django 5.0.1 on 2026-09-07 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EcomCategory',
            new_name='Category',
        ),
        migrations.DeleteModel(
            name='CategoryEntity',
        ),
    ]
