# Generated by Django 5.0.1 on 2026-09-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0002_rename_ecomcategory_category_delete_categoryentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='query',
            field=models.CharField(max_length=500),
        ),
        migrations.AddConstraint(
            model_name='searchhistory',
            constraint=models.UniqueConstraint(fields=('user', 'query'), name='unique_user_query'),
        ),
    ]
