# Generated by Django 5.0.1 on 2026-09-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0002_rbac'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rolehaspermission',
            name='uq_role_permission',
        ),
        migrations.RemoveConstraint(
            model_name='userrole',
            name='uq_user_role',
        ),
        migrations.AlterUniqueTogether(
            name='rolehaspermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
