# Generated by Django 5.0.1 on 2026-09-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0003_search_history_upsert_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='updated_at',
        ),
    ]
