# Generated by Django 5.0.1 on 2026-09-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0003_remove_rolehaspermission_uq_role_permission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
